(setq-default prettify-symbols-alist '(("lambda" . "λ")
									   ("->" . "→")
									   ("->>" . "↠")
									   ("=>" . "⇒")
									   ;; ("map" . "↦")
									   ;; ("/=" . "≠")
									   ("!=" . "≠")
									   ("==" . "≡")
									   ("<=" . "≤")
									   (">=" . "≥")
									   ("=<<" . "=≪")
									   (">>=" . "≫=")
									   ("<=<" . "↢")
									   (">=>" . "↣")
									   ;; ("!" . "￢")
									   ("function" . "ƒ")
									   ("&&" . "∧")
									   ("||" . "∨")))

(defvar-local yzs/symbols-org-mode '(
									 ("TODO" . "")
									 ("WAIT" . "")
									 ("DONE" . "")
									 ("[ ]" . "☒")
									 ("[X]" . "☑")
									 ("[-]" . "☐")
									 ("#+BEGIN_SRC" . "")
									 ("#+END_SRC" . "―")
									 ("#+begin_src" . "")
									 ("#+end_src" . "―")
									 ("#+begin_example" . "")
									 ("#+end_example" . "―")
									 ("#+BEGIN_EXAMPLE" . "")
									 ("#+END_EXAMPLE" . "―")
									 ))

(defmacro yzs/add-prettify-symbols-to-mode (mode-hook &rest symbols-list)
  "Add Prettify Symbols To Mode "
  `(add-hook ,mode-hook (lambda ()
						  (setq prettify-symbols-alist (default-value  'prettify-symbols-alist))
						  (if (listp (quote ,symbols-list))
							  (dolist (symbol-item  ',symbols-list)
								(setq prettify-symbols-alist
									  (append prettify-symbols-alist (eval symbol-item)))))
						  (prettify-symbols-mode 1))))
(if (display-graphic-p)
	(progn
	  (yzs/add-prettify-symbols-to-mode 'org-mode-hook yzs/symbols-org-mode)
	  (yzs/add-prettify-symbols-to-mode 'corfu-mode-hook nil)
	  )
  )

(provide 'default-prettify-symbols)
